#!/bin/bash
#Get all of a flickr users photos, and their metadata.
#Usage: ./flickrgrabr ${USERNAME} ${COLLECTION}

DATE_STOP=201206
if [ -z $1 ]; then 
    echo -e "!!! You must supply a a flickr username !!!\nUsage: ./flickrgrabr \${USERNAME}" 
    exit 1
else
    USER="$1"
fi
if [ -z $2 ]; then 
    COLLECTION='ourmedia'
else
    COLLECTION="$2"
fi

mkdir -p $USER
numPages=`curl -s http://www.flickr.com/photos/$USER/|grep -oE "/photos/$USER/page.*/\">.*</a>"|tail -n1|tr "><" " "|awk '{print $2}'`
echo -e "INFO::\t"$USER" $numPages pages of photos."
cd $USER

for page in `seq 1 $numPages`
do
    if [ -a `pwd`/"$USER"_$page.html ]
    then
        continue
    else
        echo -e "DOWNLOADING::\t`pwd`/"$USER"_$page.html"
        wget -q -c -O "$USER"_$page.html http://www.flickr.com/photos/"$USER"/page$page
    fi
done

for imagePage in *
do
    uploaded_date=$(grep -o -P "(?<=/photos/$USER/archives/date-posted/)[0-9]{4}/[0-9]{2}" $imagePage | head -1 | sed 's/\///g')
    if [ $uploaded_date -lt $DATE_STOP ]
    then
        continue
    else
        for ID in `cat $imagePage|grep photo_container|grep -oE "/photos/$USER/[0-9]*/"|grep -oE "/[0-9]*/"|sed 's/\///g'`
        do
            echo -e "PROCESSING::\t`pwd`/$USER-$ID"
            ../flickrGrabImage "$USER" "$ID"
        done
    fi
done

echo -e "\n\nGenerating Archive.org metadata files ...\n\n"
/home/jake/.virtualenvs/default/bin/python /1/incoming/tmp/FlickrFckr/flickr2ia.py $USER $COLLECTION
